# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import item_methods_pb2 as item__methods__pb2


class ItemMethodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItens = channel.unary_unary(
                '/ItemMethods/GetItens',
                request_serializer=item__methods__pb2.Message.SerializeToString,
                response_deserializer=item__methods__pb2.Message.FromString,
                )
        self.PopItem = channel.unary_unary(
                '/ItemMethods/PopItem',
                request_serializer=item__methods__pb2.Position.SerializeToString,
                response_deserializer=item__methods__pb2.Item.FromString,
                )


class ItemMethodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PopItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemMethodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItens': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItens,
                    request_deserializer=item__methods__pb2.Message.FromString,
                    response_serializer=item__methods__pb2.Message.SerializeToString,
            ),
            'PopItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PopItem,
                    request_deserializer=item__methods__pb2.Position.FromString,
                    response_serializer=item__methods__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ItemMethods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemMethods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMethods/GetItens',
            item__methods__pb2.Message.SerializeToString,
            item__methods__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PopItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemMethods/PopItem',
            item__methods__pb2.Position.SerializeToString,
            item__methods__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
